### ISSUE TITLE
4.10 build is broken

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/recipe-reporting-tools#23]
https://app.travis-ci.com/github/silverstripe/recipe-reporting-tools/builds/242436331

We need to address this failure before we tag the RC.

# Acceptance critera
- [x] All the build matrix are green

**Comment by emteknetnz** [comment]
Related - has details about why it's broken - https://github.com/silverstripeltd/product-issues/issues/512#issue-1073994124

**Comment by maxime-rainville** [comment]
That's been addressed
